### ISSUE TITLE
Class 'SQLite3' not found

### ISSUE THREAD

**Issue by marcos-queiroz** [dotsistemas/wpanel#25]
Primeiramente, meus parabéns pelo projeto.

Acabei de clonar seu projeto, mas não funcionou.

> An uncaught Exception was encountered
>
> Type: Error
> 
> Message: Class 'SQLite3' not found
> 
> Filename: C:\xampp\htdocs\wpanel\sys\database\drivers\sqlite3\sqlite3_driver.php
> 
> Line Number: 89

Sabe o que pode ser? Nunca usei o SQL Lite com CI.

**Comment by fabiopsy** [comment]
Olá, Marcos!

Se você utiliza **mysql**, você pode alterar o arquivo **wpanel/public/config/database.php** e substituir driver **'sqlite3'** por **'mysqli'**, na linha **84** _(development)_ ou na linha **109** _(production)_.

Kind Regards,
Fábio.

**Comment by elieldepaula** [comment]
Olá Marcos, obrigado.

Eu imagino que você precise instalar o sqlite no windows, como eu não uso este ambiente de desenvolvimento (windows + xampp), acredito que ele não esteja encontrando as bibliotecas do SQLite. Se conseguir nos dê um feedback. De qualquer forma farei uns testes em maquina virtual mesmo.

Anyway, você pode fazer como o @fabiospy comentou acima, usando MySQL em vez do SQLite.

**Comment by marcos-queiroz** [comment]
Imaginei que a configuração de qual base usar, seria depois de preencher o formulário que é exibido nesse tutorial: [Novo Instalador](http://wpanel.org/post/novo-instalador-do-wpanel-cms.html)

Por isso minha pergunta.

@fabiopsy sugeriu mudar o arquivo de configuração para usar o MySQL, só que não teria sentido o formulário de configuração, pois teremos que fazer manualmente de qualquer forma.

Como disse antes, parabéns pelo projeto.

**Comment by elieldepaula** [comment]
Então, inicialmente eu tinha pensado num instalador de verdade, onde o usuario roda o CMS e ele ja pede as informações e em seguida gerasse os arquivos necessários para a configuração, talvez um que até já baixasse os arquivos e tal, mas não fui bem sucedido por algumas restrições do CI, porém ainda não descartei a ideia totalmente, mas resolvi priorizar outras coisas no projeto.

Como o projeto é voltado para 'devs' e não 'operadores de software', essa configuração de conexão ficou manual, porém a criação das tabelas foi automatizada com os Migrations. 

O form que você indicou não é mais usado, então teriamos que ver que versão/release está usando. Atualmente o form do 'setup' só cria um usuário administrador inicial. 

Basicamente a instalação se resume em subir os arquivos, definir a conexão e acessar link/setup ou link/index.php/setup.

**Comment by elieldepaula** [comment]
Reinterando, com o volume de feedbacks que tive, estamos remodelando todo o projeto na versão 4, até o site está passando por mudanças, espero publicar tudo nos proximos dias de acordo com meu volume de trabalho aqui, e espero que curtam :)

**Comment by marcos-queiroz** [comment]
Bacana, realmente o formulário não aparece, mudei para MySQL e funcionou blz.
Assim que estiver mais familiarizado com seu projeto poderei ajudar.

**Comment by elieldepaula** [comment]
Ótimo @marcos-queiroz, se precisar é só chamar. 
Valeu!
